### ISSUE TITLE
When i open the login/register page i get exit teks

### ISSUE THREAD

**Issue by chimemoo** [riedayme/Kurteyki#2]
![image](https://user-images.githubusercontent.com/34398865/80311435-d225d780-8809-11ea-88f1-f713f9f471b1.png)

**Comment by riedayme** [comment]
which version of php are you using?

make sure you use php version 7 and above, you can download xampp php 7 here:
[https://www.apachefriends.org/xampp-files/7.3.16/xampp-windows-x64-7.3.16-1-VC15-installer.exe](https://www.apachefriends.org/xampp-files/7.3.16/xampp-windows-x64-7.3.16-1-VC15-installer.exe)

if you still can't, then there's something wrong with the code.

the code is still a lot of damage so just make it study material.

**Comment by chimemoo** [comment]
My PHP version is 7.3.9

**Comment by riedayme** [comment]
the project has update, download and install again :+1:
